---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
  # use ansible-galaxy to setup homebrew
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']      

  tasks:
    - include_tasks: tasks/tools.yml
      tags: ['tools']

    - include_tasks: tasks/dev-tools.yml
      tags: ['devtools']

    - include_tasks: tasks/dev-env.yml
      tags: ['devenv']      